-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 19:08:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema repository
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema repository
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repository` ;
USE `repository` ;

-- -----------------------------------------------------
-- Table `repository`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repository`.`CUSTOMERS` (
  `CUSTOMERNUMBER` INT NOT NULL,
  `CUSTOMERNAME` VARCHAR(50) NULL DEFAULT NULL,
  `PHONE` VARCHAR(50) NULL DEFAULT NULL,
  `CITY` VARCHAR(50) NULL DEFAULT NULL,
  `STATE` VARCHAR(50) NULL DEFAULT NULL,
  `POSTALCODE` VARCHAR(15) NULL DEFAULT NULL,
  `COUNTRY` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`CUSTOMERNUMBER`));


-- -----------------------------------------------------
-- Table `repository`.`DIM_TIME`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repository`.`DIM_TIME` (
  `TIME_ID` VARCHAR(10) NOT NULL,
  `MONTH_ID` INT NULL DEFAULT NULL,
  `YEAR_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`TIME_ID`));


-- -----------------------------------------------------
-- Table `repository`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repository`.`ORDERS` (
  `ORDERNUMBER` INT NOT NULL,
  `ORDERDATE` TIMESTAMP NULL,
  `REQUIREDDATE` TIMESTAMP NULL,
  `SHIPPEDDATE` TIMESTAMP NULL,
  `STATUS` VARCHAR(15) NULL DEFAULT NULL,
  `CUSTOMERNUMBER` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ORDERNUMBER`));


-- -----------------------------------------------------
-- Table `repository`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repository`.`PRODUCTS` (
  `PRODUCTCODE` VARCHAR(50) NOT NULL,
  `PRODUCTNAME` VARCHAR(70) NULL DEFAULT NULL,
  `PRODUCTLINE` VARCHAR(50) NULL DEFAULT NULL,
  `PRODUCTSCALE` VARCHAR(10) NULL DEFAULT NULL,
  `PRODUCTVENDOR` VARCHAR(50) NULL DEFAULT NULL,
  `QUANTITYINSTOCK` SMALLINT NULL DEFAULT NULL,
  `BUYPRICE` BIGINT NULL DEFAULT NULL,
  `MSRP` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCTCODE`));


-- -----------------------------------------------------
-- Table `repository`.`FACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repository`.`FACT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ORDERNUMBER` INT NULL,
  `CUSTOMERNUMBER` INT NULL,
  `PRODUCTCODE` VARCHAR(50) NULL,
  `TIME_ID` VARCHAR(10) NULL,
  `SALES` DOUBLE NULL,
  `QUANTITY` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_FACT_ORDERS1_idx` (`ORDERNUMBER` ASC),
  INDEX `fk_FACT_PRODUCTS1_idx` (`PRODUCTCODE` ASC),
  INDEX `fk_FACT_DIM_TIME1_idx` (`TIME_ID` ASC),
  CONSTRAINT `fk_FACT_CUSTOMERS`
    FOREIGN KEY (`CUSTOMERNUMBER`)
    REFERENCES `repository`.`CUSTOMERS` (`CUSTOMERNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_ORDERS1`
    FOREIGN KEY (`ORDERNUMBER`)
    REFERENCES `repository`.`ORDERS` (`ORDERNUMBER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_PRODUCTS1`
    FOREIGN KEY (`PRODUCTCODE`)
    REFERENCES `repository`.`PRODUCTS` (`PRODUCTCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACT_DIM_TIME1`
    FOREIGN KEY (`TIME_ID`)
    REFERENCES `repository`.`DIM_TIME` (`TIME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
